version: '3.8'

services:
  app:
    build: .
    container_name: medassis-app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal
      - MINIO_ENDPOINT=host.docker.internal
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - medassis-network

networks:
  medassis-network:
    driver: bridge
